#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <sourcefile>"
  exit 1
fi

# make a temporary directory to put intermediate trash
tmpdir=$(mktemp -d)
tmpfile=$tmpdir/deps


# get directory of file relative to the src/ directory
filename=$1
relativedir=$(dirname $filename | sed 's/src//' | cut -d'/' -f2-)
if [[ $relativedir == "" ]]; then
  relativedir="."
fi

# Go through source file and extract the header filenames from lines like     #include "filename.h"
grep -F "#include" $filename | grep -F '"' | awk -F'//' '{print $1}' | grep -F "#include" | awk '{print $2}' | cut -d'"' -f2 > $tmpfile

# prepend with both the relative directory and the include/ directory
cat $tmpfile | sed -e "s:^:${relativedir}/:" | sed -e "s:^\./::" | sed -e "s:^:include/:"
rm -r $tmpdir
